



```{r}

library(ISLR)
library(corrplot)
library(tidyverse)
library(readr)
library(ggplot2)
library(dplyr)
library(caret)
library(micset)


```


```{r}
data <- read_csv("data.csv")

dim_desc(data)
```
```{r}
names(data)
```
```{r}
summary(data)
```
```{r}
data = data %>% mutate_if(is.character, as.factor)
data$SeniorCitizen=as.factor(data$SeniorCitizen)
summary(data$SeniorCitizen)
data %>% map(~ sum(is.na(.)))
```

```{r}
data= data%>%mutate(TotalCharges = replace(TotalCharges,is.na(TotalCharges),median(TotalCharges, na.rm = T)))
ggplot(data) +
  geom_bar(aes(x = gender, fill = Churn), position = "dodge")
```
```{r}
data %>%
  group_by(gender,Churn) %>%
  summarise(n=n())
```
```{r}
ggplot(data) +
  geom_bar(aes(x = SeniorCitizen, fill = Churn), position = "dodge")
```
```{r}
data %>%
  group_by(SeniorCitizen) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n))
```

```{r}
ggplot(data) +
  geom_bar(aes(x=Partner, fill = Churn), position = "dodge")
```
```{r}
data %>%
  group_by(Partner) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n))
```

```{r}
data %>%
  group_by(Partner, Churn) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n))
```
```{r}
ggplot(data) +
  geom_bar(aes_string(x="Dependents", fill="Churn"), position = "dodge")
```
```{r}
data %>% group_by(Dependents, Churn) %>%
  summarise(n=n()) %>%
  mutate(freq = n / sum(n))
```
```{r}
data %>% group_by(Dependents) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n))
```
```{r}
ggplot(data, aes(x = SeniorCitizen, y = TotalCharges)) +
  geom_boxplot()
```
```{r}
ggplot(data, aes(x = Partner, y = TotalCharges)) +
  geom_boxplot()
```
```{r}
data %>%
  select(SeniorCitizen, Churn, TotalCharges, tenure) %>%
  filter(SeniorCitizen == 1, Churn == "Yes") %>%
  summarize(n = n(),
            total = sum(TotalCharges),
            avg_tenure = sum(tenure)/n)
```
```{r}
data %>%
  select(Partner, Churn, TotalCharges, tenure) %>%
  filter(Partner == "No", Churn == "Yes") %>%
  summarise(n = n(),
            total = sum(TotalCharges),
            avg_tenure = sum(tenure)/n)
```
```{r}
data %>%
  select(Dependents, Churn, TotalCharges, tenure) %>%
  filter(Dependents == "No", Churn == "Yes") %>%
  summarise(n = n(),
            total = sum(TotalCharges),
            avg_tenure = sum(tenure)/n)
```

```{r}
dependents = data %>% filter(Dependents == "No")
```

```{r}
ggplot(dependents) +
  geom_bar(aes(x=PaymentMethod,fill=Churn), position = "dodge")
```

```{r}

```

